### ISSUE TITLE
Add maps volume to container

### ISSUE THREAD

**Issue by jpvt** [jpvt/laser_autonomous_exploration#10]
In the current implementation of our Docker container, we do not have a dedicated volume for storing the generated maps from the simulation. To improve the usability and ease of access to these maps, we need to create a volume mounted to the container and persist the maps even after the container is stopped or removed.

To address this issue, please follow these steps:

1. Modify the `docker-compose.yml` file to define a new volume called maps. The updated file should look like this:
  ```yml
  services:
    laser_l1br:
      build: .
      container_name: laser_l1br
      volumes:
        - maps:/maps
  
  volumes:
    maps:
  ```
2. Update the project's launch file command to include the necessary arguments for saving the generated maps to the /maps directory inside the container.
3. Update the SLAM Toolbox configuration file to specify the path where the maps should be saved. Make sure to use the `/maps` directory as the output path.
4. Update the `README.md` file with instructions on how to access the maps from the container's volume, including any necessary commands for copying the maps from the container to the host machine.

Once these changes have been implemented and tested, please submit a pull request for review.
